// <auto-generated />
using System;
using GestionLicencias.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionLicencias.Infrastructure.Migrations
{
    [DbContext(typeof(GestionLicenciasDbContext))]
    [Migration("20260618164544_UpdateConcurrencyTokens")]
    partial class UpdateConcurrencyTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GestionLicencias.Core.Domain.Entities.BaseTramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoModulo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RUT");

                    b.ToTable("Tramites", (string)null);

                    b.HasDiscriminator<string>("TipoModulo").HasValue("BaseTramite");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestionLicencias.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestionLicencias.Core.Domain.Entities.TramiteLicencia", b =>
                {
                    b.HasBaseType("GestionLicencias.Core.Domain.Entities.BaseTramite");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asiste")
                        .HasColumnType("TEXT");

                    b.Property<string>("BajadaAPam")
                        .HasColumnType("TEXT");

                    b.Property<string>("BajadaPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CambioDomicilioPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("CambioDomicilioPedidoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarpetaPedida")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiudadCambioDomicilio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contactado")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactadoParaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesbloqueadoPor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DesbloqueoAdministrativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoCarpeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoF8")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCitacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesbloqueo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDigitalizacionCarpeta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaImpresion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPenultimaCarpeta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRecepcionPam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaSubidaConaset")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimaCarpeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioF8")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioLicencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdoneidadMoral")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpresaPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarAtencion")
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarOrigenCambioDomicilio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notificado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Otorgamiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeticionCambioDomicilio")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecibidaEnPamPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoLicencia")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("TramiteLicencia");
                });
#pragma warning restore 612, 618
        }
    }
}
